prezentaition/StoreRCModel.Web/Models/Clart.cs
namespace StoreRCModel.Web.Models
{
    public class Clart
    {
        public int OrderId {get;}
        public int TotalCount { get; set; }
        public decimal TotalPrice { get; set; }
        public Clart(int orderId) 
        {
            OrderId = orderId;
            TotalCount = 0;
            TotalPrice = 0m;
        }
    }
}

prezentaition/StoreRCModel.Web/Models/ErrorViewModel.cs
namespace StoreRCModel.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

prezentaition/StoreRCModel.Web/Models/OrderItemModel.cs
namespace StoreRCModel.Web.Models
{
    public class OrderItemModel
    {
        public int NumberRCModel { get; set; }
        public string NameRCModel { get; set; }
        public string TypeRCModel { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
    }
}

prezentaition/StoreRCModel.Web/Models/OrderModel.cs
using StoreRCModels;

namespace StoreRCModel.Web.Models
{
    public class OrderModel
    {
        public int Id { get; set; }
        public OrderItemModel[] Items { get; set; } = new OrderItemModel[0];
        public int TotalCount { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

prezentaition/StoreRCModel.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StoreRCModel.Web.Models;
using System.Diagnostics;

namespace StoreRCModel.Web.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

prezentaition/StoreRCModel.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using StoreRCModel.Web.Models;
using StoreRCModels;
using System.Linq;

namespace StoreRCModel.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IRCModelsRepository modelsRepository;
        private readonly IOrderRepository ordersRepository;

        public OrderController(IRCModelsRepository modelsRepository, IOrderRepository ordersRepository)
        {
            this.modelsRepository = modelsRepository;
            this.ordersRepository = ordersRepository;
        }
        public IActionResult Index()
        {
           
            if (HttpContext.Session.TryGetCart(out Clart clart))
            {
                var order = ordersRepository.GetById(clart.OrderId);
                OrderModel model = Map(order);
                return View(model);
            }
            return View("Empty");

        }

        private OrderModel Map(Order order)
        {
            var rcmodelIds = order.Items.Select(item => item.ModelId);
            var rcmodels = modelsRepository.GetAllById(rcmodelIds);
            var itemModels = from item in order.Items
                             join rcmodel in rcmodels on item.ModelId equals rcmodel.numberRCModel
                             select new OrderItemModel
                             {
                                 NumberRCModel = rcmodel.numberRCModel,
                                 NameRCModel = rcmodel.nameRCModel,
                                 TypeRCModel = rcmodel.typeRCModel,
                                 Color = rcmodel.color,
                                 Price = item.Price,
                                 Count = item.Count,
                             };

            return new OrderModel
            {
                Id = order.Id,
                Items = itemModels.ToArray(),
                TotalCount = order.TotalCount,
                TotalPrice = order.TotalPrice,
            };
        }
        public IActionResult AddItem(int id)
        {
            Order order;
            Clart clart;
            if(HttpContext.Session.TryGetCart(out clart))
            {
                order = ordersRepository.GetById(clart.OrderId);
            }
            else
            {
                order = ordersRepository.Create();
                clart = new Clart(order.Id);
            }
            var model = modelsRepository.GetById(id);
            order.AddItem(model, 1);
            ordersRepository.Update(order);

            clart.TotalCount = order.TotalCount;
            clart.TotalPrice = order.TotalPrice;

            HttpContext.Session.Set(clart);
            return RedirectToAction("Index","RCModel", new {id});
        }
    }
}

prezentaition/StoreRCModel.Web/Controllers/RCModelController.cs
using Microsoft.AspNetCore.Mvc;
using StoreRCModel.Memory;
using StoreRCModels;

namespace StoreRCModel.Web.Controllers
{
    public class RCModelController : Controller
    {
        private IRCModelsRepository rcmodelsRepository;
        public RCModelController(IRCModelsRepository rcmodelsRepository)
        {
            this.rcmodelsRepository = rcmodelsRepository;
        }
        public IActionResult Index(int id)
        {
            RCModel rcmodel = rcmodelsRepository.GetById(id);
            return View(rcmodel);
        }
    }
}

prezentaition/StoreRCModel.Web/Controllers/searchController.cs
using Microsoft.AspNetCore.Mvc;
using StoreRCModels;
using System.Linq;

namespace StoreRCModel.Web.Controllers
{
    public class searchController : Controller
    {
        private readonly RCModelService rcmodelService;

        public searchController(RCModelService rcmodelService)
        {
            this.rcmodelService = rcmodelService;
        }
        public IActionResult Index(string query)
        {
            var rcmodels = rcmodelService.GetAllByQuery(query);
            return View(rcmodels);
        }
    }
}

prezentaition/StoreRCModel.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Магазин РУмоделей";
}

prezentaition/StoreRCModel.Web/Views/Order/Empty.cshtml
@{
    ViewData["Title"] = "Корзина пуста";
}

<h1>Корзина пуста</h1>

prezentaition/StoreRCModel.Web/Views/Order/Index.cshtml
@model OrderModel
@{
    ViewData["Title"] = "Корзина";
}

<h1>Корзина</h1>
<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Тип</th>
            <th scope="col">Название</th>
            <th scope="col">Цвет</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Items.Length; i++)
        {
            <tr>
                <td class="text-right">@(i + 1)</td>
                <td>@Model.Items[i].TypeRCModel</td>
                <td>@Model.Items[i].NameRCModel</td>
                <td>@Model.Items[i].Color</td>
                <td class="text-right">@Model.Items[i].Count</td>
                <td class="text-right">@Model.Items[i].Price</td>
                <td class="text-center">
                    <form class="form-inline" action="@Url.Action("RemoveItem", "Order")" method="post">
                        <input type="hidden" name="bookId" value="@Model.Items[i].NumberRCModel" />
                        <button class="btn btn-danger" type="submit">Удалить</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого</td>
            <td class="text-right">@Model.TotalCount</td>
            <td class="text-right">@Model.TotalPrice</td>
        </tr>
    </tfoot>
</table>

prezentaition/StoreRCModel.Web/Views/RCModel/Index.cshtml
@model StoreRCModels.RCModel

@{
    ViewData["Title"] = Model.nameRCModel;
}

<h1>@Model.nameRCModel</h1>
<p><strong>@Model.typeRCModel</strong></p>
<p>@Model.description</p>
<p>Цена <strong>@Model.price</strong></p>
<form action="@Url.Action("AddItem","Order")" method="post">
    <input type="hidden" name="id" value="@Model.numberRCModel"/>
    <button class="btn btn-success" type="submit">В корзину</button>
</form>

prezentaition/StoreRCModel.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Магазин РУмоделей</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreRCModel.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Магазин РУмоделей</a>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("Index", "search")" method="get">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="название или тип" /> 
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">искать</button>
            </form> 
            <span class="navbar-text modal-lg-auto">
                @{
                    if(Context.Session.TryGetCart(out Clart clart)&& clart.TotalCount > 0)
                    {
                        <a href="@Url.Action("Index","Order")">Товаров @clart.TotalCount на сумму @clart.TotalPrice</a>
                    }
                    else
                    {
                        @: корзина пуста
                    }
                }
            </span>

            
        </nav>
    </header>
    <div class="container">
        <main> 
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

prezentaition/StoreRCModel.Web/Views/search/Index.cshtml
@model StoreRCModels.RCModel[];

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if (Model.Length == 0)
{
    <p> Ничего не найдено.</p>
}
else
{
    <ul>@foreach(var rcmodel in Model)
        {
            <li><a href="@Url.Action("Index","RCModel", new{id = rcmodel.numberRCModel })"> @rcmodel.nameRCModel</a></li>
        }</ul>
}